import type { NextConfig } from "next";

/**
 * Next.js configuration.
 *
 * - `output: undefined` (default) for the Vercel reference deployment.
 *   Run `OUTPUT=export pnpm build` to produce a static export for the IPFS mirror.
 * - CSP and other security headers live here; tightened in Phase 14.
 *
 * Phase 14 — Content Security Policy.
 *
 * The CSP is tight by intent. `connect-src` enumerates the exact endpoints the
 * client speaks to: Horizon (mainnet + testnet) for classic, Soroban RPC
 * (mainnet via Gateway + testnet) for the v14 SDK's `rpc.Server`, Refractor for
 * multisig coordination, the Aquarius AMM API for pool metadata, the Soroswap
 * Finance API for the aggregator quote endpoint, and Friendbot for the testnet
 * integration corpus path. Any new endpoint added in a later phase MUST be
 * added here at the same time; the CI gate fails if a fetch is issued to a
 * host not on this list.
 *
 * `script-src 'self' 'wasm-unsafe-eval'` — `'self'` only (no inline). The
 * `'wasm-unsafe-eval'` source-expression is the Phase 26 / CSP Level 3 token
 * that permits compiling and instantiating WebAssembly modules without
 * re-allowing arbitrary `eval()`; the Stellar SDK's signature codepaths pull
 * in a WASM payload via `noble` cryptos.
 *
 * `style-src 'self' 'unsafe-inline'` — Tailwind 4 + shadcn vendor everything,
 * but inline `<style>` blocks generated by Next.js for CSS-in-JS critical
 * styles still need `'unsafe-inline'`. We do NOT allow `'unsafe-inline'` for
 * scripts.
 *
 * `frame-ancestors 'none'` + `X-Frame-Options: DENY` — defence in depth
 * against clickjacking; the demolisher must never be loaded inside an iframe.
 *
 * Dev mode (`next dev`) is intentionally more permissive: HMR uses inline
 * scripts and `eval`, and the dev server's overlay binds to localhost. The
 * Phase 14 CSP only applies to production builds.
 */
const isExport = process.env.OUTPUT === "export";
const isDev = process.env.NODE_ENV !== "production";

/**
 * Connect-src allow-list. Sourced from `grep -RE "https://" src/` to ensure
 * every actual outbound destination is covered. Update both this constant and
 * the grep when a new endpoint is added.
 */
const CONNECT_SRC_ENDPOINTS = [
  "https://horizon.stellar.org",
  "https://horizon-testnet.stellar.org",
  "https://horizon-futurenet.stellar.org",
  "https://soroban-rpc.mainnet.stellar.gateway.fm",
  "https://soroban-testnet.stellar.org",
  "https://rpc-futurenet.stellar.org",
  "https://api.refractor.space",
  "https://amm-api.aqua.network",
  "https://amm-api-testnet.aqua.network",
  "https://api.soroswap.finance",
  "https://friendbot.stellar.org",
  "https://friendbot-futurenet.stellar.org",
] as const;

const PRODUCTION_CSP = [
  "default-src 'self'",
  `connect-src 'self' ${CONNECT_SRC_ENDPOINTS.join(" ")}`,
  "script-src 'self' 'wasm-unsafe-eval'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

/**
 * Dev CSP: relaxed enough for Next.js HMR (inline scripts, eval, ws://) but
 * still keeps the structural directives that catch architectural regressions
 * (no third-party script hosts, no frame-ancestors).
 */
const DEV_CSP = [
  "default-src 'self'",
  `connect-src 'self' ws: wss: ${CONNECT_SRC_ENDPOINTS.join(" ")}`,
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

const config: NextConfig = {
  output: isExport ? "export" : undefined,
  reactStrictMode: true,
  poweredByHeader: false,
  images: {
    // Account Demolisher does not load remote images; tight allow-list.
    remotePatterns: [],
  },
  async headers() {
    if (isExport) {
      // Static export hosts (IPFS / Fleek) deliver their own headers.
      return [];
    }
    const csp = isDev ? DEV_CSP : PRODUCTION_CSP;
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "no-referrer" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
          // HSTS is only meaningful on HTTPS; the reference deployment is
          // Vercel-hosted with TLS enforced.
          ...(isDev
            ? []
            : [
                {
                  key: "Strict-Transport-Security",
                  value: "max-age=63072000; includeSubDomains; preload",
                },
              ]),
        ],
      },
    ];
  },
};

export default config;
